# Generated by Django 5.1 on 2025-03-07 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='companyaddress',
            table='stockplus_company_address',
        ),
        migrations.AlterModelTable(
            name='useraddress',
            table='stockplus_user_address',
        ),
    ]
