# Generated by Django 5.1 on 2025-03-10 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0004_alter_companyaddress_id_alter_useraddress_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyaddress',
            old_name='date_create',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='companyaddress',
            old_name='date_update',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='useraddress',
            old_name='date_create',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='useraddress',
            old_name='date_update',
            new_name='updated_at',
        ),
    ]
