# Generated by Django 5.1 on 2025-03-07 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='invitation',
            table='stockplus_invitation',
        ),
        migrations.AlterModelTable(
            name='notification',
            table='stockplus_notification',
        ),
        migrations.AlterModelTable(
            name='user',
            table='stockplus_user',
        ),
    ]
