# Generated by Django 5.1 on 2025-03-09 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_invitation_id_alter_notification_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_value', models.CharField(max_length=255, unique=True)),
                ('token_type', models.CharField(choices=[('verification', 'Verification'), ('password_reset', 'Password Reset'), ('invitation', 'Invitation')], max_length=20)),
                ('method', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS')], default='email', max_length=10)),
                ('expiry', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'token',
                'verbose_name_plural': 'tokens',
                'db_table': 'stockplus_token',
                'indexes': [models.Index(fields=['token_value'], name='stockplus_t_token_v_f4fac9_idx'), models.Index(fields=['token_type'], name='stockplus_t_token_t_b03e9c_idx'), models.Index(fields=['user'], name='stockplus_t_user_id_eae287_idx')],
            },
        ),
    ]
