# Generated by Django 5.1 on 2025-03-10 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_token_cache_token_create_by_token_date_create_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='invitation',
            old_name='date_create',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='invitation',
            old_name='date_update',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='date_create',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='date_update',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='token',
            old_name='date_create',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='token',
            old_name='date_update',
            new_name='updated_at',
        ),
    ]
