# Generated by Django 5.1 on 2025-03-10 14:23

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cache',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='create_by',
            field=models.CharField(blank=True, editable=False, max_length=254, null=True, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Creation date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='is_disable',
            field=models.BooleanField(default=False, verbose_name='Is disable'),
        ),
        migrations.AddField(
            model_name='user',
            name='logs',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='search',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='update_by',
            field=models.CharField(blank=True, editable=False, max_length=254, null=True, verbose_name='Updated by'),
        ),
        migrations.AddField(
            model_name='user',
            name='update_count',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Update date'),
        ),
    ]
