# Generated by Django 5.1 on 2025-03-14 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_rename_date_create_company_created_at_and_more'),
        ('user', '0008_user_cache_user_create_by_user_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='company_id',
        ),
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.ForeignKey(blank=True, help_text='The company this user belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, to='company.company'),
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
