version: "3.5"

services:
  db:
    image: postgres:16-alpine
    environment:
      LANG: fr_FR.utf8
      POSTGRES_INITDB_ARGS: --locale-provider=icu --icu-locale=fr-FR
      POSTGRES_PASSWORD: stockplus
      POSTGRES_USER: stockplus
      POSTGRES_DB: stockplus
    volumes:
      - .:/sql
      - db:/var/lib/postgresql/data
    ports:
      - 5432:5432

  adminer:
    image: adminer:latest
    ports:
      - 8090:8080

volumes:
  db:
