name: stockplus

services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile.prod
    volumes:
      - .:/app
    expose:
      - "8000"
    environment:
      - DEBUG=True
      - DATABASE=${DATABASE}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - SENDER_NAME=${SENDER_NAME}
      - SENDER_EMAIL=${SENDER_EMAIL}
      - REPLY_NAME=${REPLY_NAME}
      - REPLY_EMAIL=${REPLY_EMAIL}
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - MISSIVE_SERVICE=${MISSIVE_SERVICE}
      - SENDINBLUE_APIKEY=${SENDINBLUE_APIKEY}

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/staticfiles
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  static_volume:
