FROM python:3.10.15-alpine3.20
LABEL maintainer="ddaniomer@gmail.com"

ENV PYTHONUNBUFFERED 1

WORKDIR /app

COPY . /app/
EXPOSE 8000

RUN apk update && apk add --no-cache \
python3 python3-dev \
py3-pip py3-virtualenv \
postgresql-client postgresql-dev \
build-base musl-dev

# Create and activate the virtual environment, then install dependencies
RUN python3 -m venv /venv && \
/venv/bin/pip install --upgrade pip && \
/venv/bin/pip install --no-cache-dir -r configuration/requirements/production.txt

# Add the virtual environment to PATH
ENV PATH="/venv/bin:$PATH"

# Command to start the application
CMD ["python", "manage.py", "runserver"]
