# Generated by Django 5.1 on 2025-03-10 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_customer_id_alter_price_id_alter_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='date_create',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='date_update',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='price',
            old_name='date_create',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='price',
            old_name='date_update',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='date_create',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='date_update',
            new_name='updated_at',
        ),
    ]
