# Generated by Django 5.1 on 2024-09-05 11:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockplus', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pointofsale',
            name='manager',
        ),
        migrations.AddField(
            model_name='pointofsale',
            name='collaborators',
            field=models.ManyToManyField(related_name='assigned_point_of_sales', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pointofsale',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
