# Generated by Django 5.1 on 2024-09-20 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockplus', '0002_remove_pointofsale_manager_pointofsale_collaborators_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointofsale',
            name='is_disable',
            field=models.BooleanField(default=False, verbose_name='Is disable'),
        ),
    ]
