# Generated by Django 5.1 on 2024-10-14 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0036_remove_product_brand_remove_product_category_and_more'),
        ('stockplus', '0005_product_company_alter_productfeature_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brands', to='builder.company'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_categories', to='builder.company'),
        ),
    ]
