# Generated by Django 5.1 on 2024-10-15 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockplus', '0006_brand_company_productcategory_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='company',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='company',
        ),
        migrations.AddField(
            model_name='pointofsaleproductvariant',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
