# Generated by Django 5.1 on 2024-10-15 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0036_remove_product_brand_remove_product_category_and_more'),
        ('stockplus', '0007_remove_brand_company_remove_productcategory_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='builder.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productcategory',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_categories', to='builder.company'),
            preserve_default=False,
        ),
    ]
