# Generated by Django 5.1 on 2024-09-03 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0004_remove_invitation_created_at_invitation_cache_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invitation',
            old_name='invited_by',
            new_name='sender',
        ),
    ]
