# Generated by Django 5.1 on 2024-09-04 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0009_companyaddress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyaddress',
            old_name='street',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='useraddress',
            old_name='street',
            new_name='address',
        ),
        migrations.AlterField(
            model_name='companyaddress',
            name='country',
            field=models.CharField(default='France', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='country',
            field=models.CharField(max_length=255),
        ),
    ]
