# Generated by Django 5.1 on 2024-09-08 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0013_remove_company_owner_user_company_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('manager', 'Manager'), ('collaborator', 'Collaborator'), ('member', 'Member')], default='manager', max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Collaboration',
        ),
    ]
