# Generated by Django 5.1 on 2024-09-14 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('builder', '0015_feature_subscriptionplan_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='permission',
            field=models.ManyToManyField(limit_choices_to={'codename__in': ['stater', 'premium']}, related_name='permissions', to='auth.permission'),
        ),
    ]
