# Generated by Django 5.1 on 2024-09-14 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0017_alter_subscriptionplan_permission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptionplan',
            old_name='permission',
            new_name='permissions',
        ),
    ]
