# Generated by Django 5.1 on 2024-09-15 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0018_rename_permission_subscriptionplan_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('paused', 'Paused'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], max_length=100),
        ),
    ]
