# Generated by Django 5.1 on 2024-09-17 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0021_subscriptionpricing'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
