# Generated by Django 5.1 on 2024-09-20 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0022_subscriptionplan_active'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subscriptionpricing',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='duration_choice',
        ),
        migrations.AddField(
            model_name='subscription',
            name='interval',
            field=models.CharField(choices=[('month', 'Monthly'), ('semester', 'Semestrial'), ('year', 'Yearly')], default='month', max_length=100),
        ),
        migrations.AddField(
            model_name='subscriptionpricing',
            name='interval',
            field=models.CharField(choices=[('month', 'Monthly'), ('semester', 'Semestrial'), ('year', 'Yearly')], default='month', max_length=100),
        ),
        migrations.AddField(
            model_name='subscriptionpricing',
            name='subscription_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pricing', to='builder.subscriptionplan'),
        ),
        migrations.RemoveField(
            model_name='subscriptionpricing',
            name='duration_choice',
        ),
        migrations.RemoveField(
            model_name='subscriptionpricing',
            name='plan',
        ),
    ]
