# Generated by Django 5.1 on 2024-09-20 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0023_alter_subscriptionpricing_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='is_disable',
            field=models.BooleanField(default=False, verbose_name='Is disable'),
        ),
        migrations.AlterField(
            model_name='companyaddress',
            name='is_disable',
            field=models.BooleanField(default=False, verbose_name='Is disable'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='is_disable',
            field=models.BooleanField(default=False, verbose_name='Is disable'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='is_disable',
            field=models.BooleanField(default=False, verbose_name='Is disable'),
        ),
        migrations.AlterField(
            model_name='missive',
            name='is_disable',
            field=models.BooleanField(default=False, verbose_name='Is disable'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='is_disable',
            field=models.BooleanField(default=False, verbose_name='Is disable'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='is_disable',
            field=models.BooleanField(default=False, verbose_name='Is disable'),
        ),
        migrations.AlterField(
            model_name='subscriptionpricing',
            name='is_disable',
            field=models.BooleanField(default=False, verbose_name='Is disable'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='is_disable',
            field=models.BooleanField(default=False, verbose_name='Is disable'),
        ),
    ]
