# Generated by Django 5.1 on 2024-09-29 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0027_alter_user_email_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
