# Generated by Django 5.1 on 2024-09-30 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0028_alter_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='stripe_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
