# Generated by Django 5.1 on 2024-09-30 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('builder', '0029_subscriptionplan_stripe_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptionplan',
            options={'permissions': [('stater', 'Starter Permissions'), ('premium', 'Premium Permissions'), ('enterprise', 'Enterprise Permissions')]},
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='name',
            field=models.CharField(choices=[('stater', 'Starter'), ('premium', 'Premium'), ('enterprise', 'Enterprise')], max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='permissions',
            field=models.ManyToManyField(limit_choices_to={'codename__in': ['stater', 'premium', 'enterprise'], 'content_type__app_label': 'builder'}, related_name='permissions', to='auth.permission'),
        ),
    ]
