# Generated by Django 5.1 on 2024-09-30 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0031_subscriptionpricing_stripe_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionpricing',
            name='currency',
            field=models.CharField(choices=[('usd', 'USD'), ('eur', 'EUR'), ('xof', 'FCFA')], default='euro', max_length=10),
        ),
    ]
