# Generated by Django 5.1 on 2024-09-30 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0032_alter_subscriptionpricing_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionpricing',
            name='currency',
            field=models.CharField(choices=[('usd', 'USD'), ('eur', 'EUR'), ('xof', 'XOF'), ('xaf', 'XAF')], default='euro', max_length=10),
        ),
    ]
