# Generated by Django 5.1 on 2025-03-07 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='missive',
            table='stockplus_missive',
        ),
    ]
