# Generated by Django 5.1 on 2025-03-09 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0002_alter_missive_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missive',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
