# Generated by Django 5.1 on 2025-03-10 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0004_alter_missive_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='missive',
            old_name='date_create',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='missive',
            old_name='date_update',
            new_name='updated_at',
        ),
    ]
