# Generated by Django 5.1 on 2025-03-07 12:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PointOfSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('logs', models.JSONField(blank=True, default=dict, null=True)),
                ('is_disable', models.BooleanField(default=False, verbose_name='Is disable')),
                ('search', models.TextField(blank=True, db_index=True, null=True)),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('create_by', models.CharField(blank=True, editable=False, max_length=254, null=True, verbose_name='Created by')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('update_by', models.CharField(blank=True, editable=False, max_length=254, null=True, verbose_name='Updated by')),
                ('update_count', models.PositiveBigIntegerField(default=0)),
                ('note', models.TextField(blank=True, null=True)),
                ('cache', models.JSONField(blank=True, default=dict, null=True)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('store', 'Physical Store'), ('warehouse', 'Warehouse'), ('online', 'Online Store')], default='store', max_length=50)),
                ('opening_hours', models.CharField(blank=True, max_length=255, null=True)),
                ('closing_hours', models.CharField(blank=True, max_length=255, null=True)),
                ('collaborators', models.ManyToManyField(related_name='assigned_point_of_sales', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(blank=True, help_text='The company this point of sale belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_pos', to='company.company')),
            ],
            options={
                'verbose_name': 'Point of Sale',
                'verbose_name_plural': 'Points of Sale',
                'db_table': 'stockplus_pointofsale',
            },
        ),
        migrations.CreateModel(
            name='PosPaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('logs', models.JSONField(blank=True, default=dict, null=True)),
                ('is_disable', models.BooleanField(default=False, verbose_name='Is disable')),
                ('search', models.TextField(blank=True, db_index=True, null=True)),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('create_by', models.CharField(blank=True, editable=False, max_length=254, null=True, verbose_name='Created by')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('update_by', models.CharField(blank=True, editable=False, max_length=254, null=True, verbose_name='Updated by')),
                ('update_count', models.PositiveBigIntegerField(default=0)),
                ('note', models.TextField(blank=True, null=True)),
                ('cache', models.JSONField(blank=True, default=dict, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('requires_confirmation', models.BooleanField(default=False)),
                ('confirmation_instructions', models.TextField(blank=True, null=True)),
                ('point_of_sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pos_payment_methods', to='pointofsale.pointofsale')),
            ],
            options={
                'verbose_name': 'Payment Method',
                'verbose_name_plural': 'Payment Methods',
                'db_table': 'stockplus_paymentmethod',
            },
        ),
    ]
