# Generated by Django 5.1 on 2025-03-07 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pointofsale', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pospaymentmethod',
            table='stockplus_pospaymentmethod',
        ),
    ]
