# Generated by Django 5.1 on 2025-03-07 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointofsale', '0002_alter_pospaymentmethod_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointofsale',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Whether this is the default point of sale for quick sales.'),
        ),
    ]
