# Generated by Django 5.1 on 2025-03-09 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointofsale', '0003_pointofsale_is_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointofsale',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pospaymentmethod',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
