# Generated by Django 5.1 on 2025-03-10 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pointofsale', '0005_alter_pointofsale_id_alter_pospaymentmethod_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pointofsale',
            old_name='date_create',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='pointofsale',
            old_name='date_update',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='pospaymentmethod',
            old_name='date_create',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='pospaymentmethod',
            old_name='date_update',
            new_name='updated_at',
        ),
    ]
