# Generated by Django 5.1 on 2025-03-09 08:12

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_subscriptionplan_is_free_trial_trial_days'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feature',
            options={'verbose_name': 'Feature', 'verbose_name_plural': 'Features'},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name': 'Subscription', 'verbose_name_plural': 'Subscriptions'},
        ),
        migrations.AlterModelOptions(
            name='subscriptionplan',
            options={'permissions': [('stater', 'Starter Permissions'), ('premium', 'Premium Permissions'), ('enterprise', 'Enterprise Permissions')], 'verbose_name': 'Subscription Plan', 'verbose_name_plural': 'Subscription Plans'},
        ),
        migrations.AlterModelOptions(
            name='subscriptionpricing',
            options={'verbose_name': 'Subscription Pricing', 'verbose_name_plural': 'Subscription Pricings'},
        ),
        migrations.RemoveField(
            model_name='feature',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='company',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='subscriptionpricing',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='subscriptionpricing',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='feature',
            name='cache',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='feature',
            name='create_by',
            field=models.CharField(blank=True, editable=False, max_length=254, null=True, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='feature',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Creation date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feature',
            name='date_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Update date'),
        ),
        migrations.AddField(
            model_name='feature',
            name='logs',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='feature',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feature',
            name='search',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='feature',
            name='update_by',
            field=models.CharField(blank=True, editable=False, max_length=254, null=True, verbose_name='Updated by'),
        ),
        migrations.AddField(
            model_name='feature',
            name='update_count',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscription',
            name='cache',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='create_by',
            field=models.CharField(blank=True, editable=False, max_length=254, null=True, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Creation date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscription',
            name='date_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Update date'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='logs',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='search',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='update_by',
            field=models.CharField(blank=True, editable=False, max_length=254, null=True, verbose_name='Updated by'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='update_count',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='cache',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='create_by',
            field=models.CharField(blank=True, editable=False, max_length=254, null=True, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Creation date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='date_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Update date'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='logs',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='search',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='update_by',
            field=models.CharField(blank=True, editable=False, max_length=254, null=True, verbose_name='Updated by'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='update_count',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscriptionpricing',
            name='cache',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionpricing',
            name='create_by',
            field=models.CharField(blank=True, editable=False, max_length=254, null=True, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='subscriptionpricing',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Creation date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriptionpricing',
            name='date_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Update date'),
        ),
        migrations.AddField(
            model_name='subscriptionpricing',
            name='logs',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionpricing',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionpricing',
            name='search',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionpricing',
            name='update_by',
            field=models.CharField(blank=True, editable=False, max_length=254, null=True, verbose_name='Updated by'),
        ),
        migrations.AddField(
            model_name='subscriptionpricing',
            name='update_count',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='feature',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='feature',
            name='is_disable',
            field=models.BooleanField(default=False, verbose_name='Is disable'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='interval',
            field=models.CharField(choices=[('month', 'Monthly'), ('semester', 'Semestrial'), ('year', 'Yearly')], default='month', max_length=100),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='is_disable',
            field=models.BooleanField(default=False, verbose_name='Is disable'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('paused', 'Paused'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='is_disable',
            field=models.BooleanField(default=False, verbose_name='Is disable'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='name',
            field=models.CharField(choices=[('stater', 'Starter'), ('premium', 'Premium'), ('enterprise', 'Enterprise')], max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='subscriptionpricing',
            name='currency',
            field=models.CharField(choices=[('usd', 'USD'), ('eur', 'EUR'), ('xof', 'XOF'), ('xaf', 'XAF')], default='eur', max_length=10),
        ),
        migrations.AlterField(
            model_name='subscriptionpricing',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subscriptionpricing',
            name='interval',
            field=models.CharField(choices=[('month', 'Monthly'), ('semester', 'Semestrial'), ('year', 'Yearly')], default='month', max_length=100),
        ),
        migrations.AlterField(
            model_name='subscriptionpricing',
            name='is_disable',
            field=models.BooleanField(default=False, verbose_name='Is disable'),
        ),
        migrations.AlterField(
            model_name='subscriptionpricing',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterModelTable(
            name='feature',
            table='stockplus_feature',
        ),
    ]
