# Generated by Django 5.1 on 2025-03-07 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_remove_subscriptionplan_features_and_more'),
        ('subscription', '0003_subscriptionplan_is_free_trial_trial_days'),
    ]

    operations = [
    ]
