# Generated by Django 5.1 on 2025-03-10 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0005_alter_feature_id_alter_subscription_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feature',
            old_name='date_create',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='feature',
            old_name='date_update',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='date_create',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='date_update',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='subscriptionplan',
            old_name='date_create',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='subscriptionplan',
            old_name='date_update',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='subscriptionpricing',
            old_name='date_create',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='subscriptionpricing',
            old_name='date_update',
            new_name='updated_at',
        ),
    ]
